name: Run juint tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with: 
          java-version: 25
          cache: maven
      - run: mvn test